### ISSUE TITLE
config spam after atom restart

### ISSUE THREAD

**Issue by hlb-schmidt** [digitallyserviced/semanticolor#33]
i changed the comment color in semanticolor settings and it added this to my `~/.atom/config.cson`
```
  semanticolor:
    defaults:
      comment: "theme"
```

everything is fine.

then i restart atom and my `~/.atom/config.cson` now has this `semanticolor` entry:
```
semanticolor:
    cCakeFileLanguageCsharp:
      "attribute-name": "default"
      comment: "default"
      constant_numeric: "default"
      enabled: true
      everythingElse: "default"
      keyword: "default"
      language: "default"
      markup: "default"
      name: "default"
      operator: "default"
      primitive: "default"
      punctuation: "default"
      regexp: "default"
      source: "default"
      storage_modifier: "default"
      storage_type: "default"
      string_quoted: "default"
      support_constant: "default"
      support_type: "default"
      variable: "default"
    cLanguageC:
      "attribute-name": "default"
      comment: "default"
      constant_numeric: "default"
      enabled: true
      everythingElse: "default"
      keyword: "default"
      language: "default"
      markup: "default"
      name: "default"
      operator: "default"
      primitive: "default"
      punctuation: "default"
      regexp: "default"
      source: "default"
      storage_modifier: "default"
      storage_type: "default"
      string_quoted: "default"
      support_constant: "default"
      support_type: "default"
      variable: "default"
... and so on, not gonna post all the hundreds of lines
```

even my `defaults` entry is now bigger than before atom restart.

the `semanticolor` entry should only have values that i changed.

> ❯ atom --version
Atom    : 1.32.0
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3
